#! /usr/bin/env php
<?php

use ArtisanCms\Installer\NewCommand;
use ArtisanCms\Installer\InstallCommand;
use Symfony\Component\Console\Application;

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    require __DIR__.'/../../autoload.php';
}

$app = new Application('ArtisanCMS Studio', '0.1.22');

$app->add(new NewCommand);
$app->add(new InstallCommand);

$app->run();
