#! /usr/bin/env php
<?php

use ArtisanCms\NewCommand;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('ArtisanCMS Studio', '0.1.4');

$app->add(new NewCommand);

$app->run();
